# Generated by Django 5.2.7 on 2025-10-14 04:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.TextField()),
                ('fecha_creacion', models.DateField()),
                ('estado', models.CharField(choices=[('en_curso', 'En curso'), ('en_revision', 'En revisión final'), ('finalizado', 'Finalizado')], default='en_curso', max_length=20)),
                ('finalizado', models.BooleanField(default=False)),
                ('presupuesto_inicial', models.DecimalField(decimal_places=2, max_digits=12)),
                ('presupuesto_actual', models.DecimalField(decimal_places=2, max_digits=12)),
                ('creador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proyectos_creados', to=settings.AUTH_USER_MODEL)),
                ('encargado', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proyectos_asignados', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HistorialPresupuesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('presupuesto_actual', models.DecimalField(decimal_places=2, max_digits=12)),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='core.proyecto')),
            ],
        ),
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actividad', models.CharField(max_length=255)),
                ('fecha', models.DateField()),
                ('modificacion', models.DateTimeField(auto_now=True)),
                ('ingreso', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('egreso', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actividades', to='core.proyecto')),
            ],
        ),
    ]
